# Makefile que gera o CircuitRouter-SeqSolver | CircuitRouter-SimpleShell | CircuitRouter-ParSolver

all:	
	(cd CircuitRouter-ParSolver/; make)
	(cd CircuitRouter-SeqSolver/; make)

clean:
	(cd CircuitRouter-ParSolver/; make clean)
	(cd CircuitRouter-SeqSolver/; make clean)